### ISSUE TITLE
Add Firefox-Profiler based visualization

### ISSUE THREAD

**Issue by dpsoft** [dpsoft/ap-agent#6]
I think it will be an easy integration using https://github.com/parttimenerd/jfrtofp. Maybe @parttimenerd can help us

* https://profiler.firefox.com/

**Comment by parttimenerd** [comment]
Yes, I'm sure to help. It should be (for starters) enough to just convert the file and pass the Firefox Profiler page the URL, e.g. something like "http://localhost:8080/from-url/http%253A%252F%252Flocalhost%253A8080%252Ffiles%252Fp". Or you use https://github.com/parttimenerd/jfrtofp-server directly.

Be aware that the API is not yet final and it is currently under development :)

**Comment by dpsoft** [comment]
Completed with #11

**Comment by dpsoft** [comment]
Completed with #11
